Add picture of myself to page, scaled and in the center. Add quick wr…
Kwameoab/step pull request #2
Opened 2020-05-27 17:57 UTC by Kwameoab

…ite-up about myself. Change button and contents that show up when button is clicked on.

2020-05-27 18:39 UTC, ljfranklin requested changes

2020-05-27 18:39 UTC, ljfranklin commented on portfolio/src/main/webapp/index.html
> +      <p>Hello! My name is Kwame Ampadu-Boateng. I a currently a rising
Add a newline after `<p>`, makes it easier to see where the tag ends if the end tag is lined up with the start tag. e.g.

```
<p>
  some text.
  some more text
</p>
```

2020-05-27 18:39 UTC, ljfranklin commented on portfolio/src/main/webapp/index.html
> +        <img src="/images/Self.jpg" width="300" height="350"
Indent the `<img>` tag back one level. All children within a given element should have the same indentation.

2020-05-27 18:43 UTC, ljfranklin requested changes
Also going forward you should add a line break in your commit messages so it doesn't get cut off when displaying in GitHub. The first line should also be a summary. E.g.

```
Add first pass at portfolio homepage

- Add picture of myself to page, scaled and in the center
- Add quick write-up about myself
- Change button and contents that show up when button is clicked on.
```

2020-05-27 21:11 UTC, ljfranklin commented
@Kwameoab when you're finished making changes you can click Request next to my name under Reviewers and I'll get a notification to take another look.

2020-05-27 21:20 UTC, Kwameoab commented
> @Kwameoab when you're finished making changes you can click Request next to my name under Reviewers and I'll get a notification to take another look.

Thank you so much for telling me that, I was confused on what the next step for me was.

2020-05-28 13:09 UTC, ljfranklin commented on portfolio/src/main/webapp/index.html
> +      <p>Hello! My name is Kwame Ampadu-Boateng. I a currently a rising
Nit (short for nitpick): put a line break after the start tag if the contents span multiple lines, e.g. 

```
<p>
    Hello! My name is Kwame Ampadu-Boateng. I a currently a rising
    ...
</p>
```

2020-05-28 13:09 UTC, ljfranklin approved these changes

2020-05-28 14:06 UTC, merged